# Generated by Django 4.2.16 on 2024-11-09 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("prn", models.CharField(max_length=10)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("Computer", "Computer"),
                            ("Electrical", "Electrical"),
                            ("Civil", "Civil"),
                            ("Mechanical", "Mechanical"),
                            ("Instrumentation", "Instrumentation"),
                            ("Electronics and Tele.", "Electronics and Tele."),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("1st", "1st"),
                            ("2nd", "2nd"),
                            ("3rd", "3rd"),
                            ("4th", "4th"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Book_issued", models.CharField(max_length=50)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "Student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="APP.student"
                    ),
                ),
            ],
        ),
    ]
